### ISSUE TITLE
zmb's "start_domain_test" does not know about the "queue" parameter

### ISSUE THREAD

**Issue by anandb-ripencc** [zonemaster/zonemaster-backend#1002]
I want to use the "zmb" utility to submit tests into a specific queue. However, it doesn't yet know about queues. It would be useful if we could also specify "--queue N" when submitting a test.

**Comment by matsduf** [comment]
That should not be too complicated.

**Comment by anandb-ripencc** [comment]
I've created #1006 since it seemed like quite a simple and easy change. I've tested it on my Zonemaster installation, and it works as expected. Would be nice if you could merge it in time for v2022.1

**Comment by matsduf** [comment]
Resolved by #1006.
