### ISSUE TITLE
get_test_history says "ok" but test has not even started and other errors

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#1009]
Comare with #888 that covers the same issue, which was reported to be solved by #942.

-----

I stopped the test agent:
```
# /usr/local/etc/rc.d/zm_testagent status
zm_testagent is not running.
```

I created a test of domain "arpa":
```
# zmb start_domain_test --domain arpa
{"id":1,"result":"bf522d81f00a8e38","jsonrpc":"2.0"}
```

The progress of this test is zero:
```
# zmb test_progress --test-id bf522d81f00a8e38 | jq
{
  "jsonrpc": "2.0",
  "result": 0,
  "id": 1
}
```

But test history says that the test bf522d81f00a8e38 is `OK`:
```
# zmb get_test_history --domain arpa | jq .
{
  "jsonrpc": "2.0",
  "result": [
    {
      "undelegated": false,
      "overall_result": "ok",
      "id": "bf522d81f00a8e38",
      "creation_time": "2022-05-16 14:08:33"
    },
(...)
  ],
  "id": 1
}
```

I also expected  get_test_results() to return an error when progress is not 100 -- API document says "that test must have been completed" -- but that is not very explicit. Previously the behavior was to return an error when the test was not completed.
```
# zmb get_test_results --test-id bf522d81f00a8e38 --lang en | jq
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "hash_id": "bf522d81f00a8e38",
    "results": [],
    "params": {
      "priority": 10,
      "nameservers": [],
      "ds_info": [],
      "ipv6": true,
      "ipv4": true,
      "profile": "default",
      "queue": 0,
      "domain": "arpa"
    },
    "creation_time": "2022-05-16 14:08:33",
    "id": 6
  }
}
```

**Comment by pnax** [comment]
Just tried your example, and I get an empty history:

```
$ ./script/zmb start_domain_test --domain arpa
{"result":"74e604cfaf066060","id":1,"jsonrpc":"2.0"}
$ ./script/zmb test_progress --test-id 74e604cfaf066060
{"id":1,"jsonrpc":"2.0","result":0}
$ ./script/zmb get_test_history --domain arpa
{"jsonrpc":"2.0","id":1,"result":[]}
```

Are you using the latest development code? Could you double check?

**Comment by matsduf** [comment]
> Are you using the latest development code? Could you double check? Can you query for the test's progress again, after you get the unexpected results?

It is development code, but maybe not latest. I will rebuild and report.

**Comment by matsduf** [comment]
Later code resolves the issue.
