### ISSUE TITLE
Remove key "id" from the return value of API method "get_test_results"

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#1062]
From the release notes of v9.0.0 (v2022.1):
> API method "get_test_results" returns key "id", which is now deprecated and will be removed in v2022.2 release. See [docs/API.md#api-method-get_test_results](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/API.md#api-method-get_test_results). (https://github.com/zonemaster/zonemaster-backend/pull/949)

**Comment by pnax** [comment]
This was done in #946. I'm changing the milestone and closing this issue.
