### ISSUE TITLE
Remove "creation_time" key from the return value of API methods "get_test_results" and "get_test_history"

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#1063]
From the release notes of v9.0.0 (v2022.1):

> The API methods "get_test_results" and "get_test_history" returns two keys with the same timestamp in different formats. The "creation_time" key is deprecated and will be removed with release v2023.1. Use the "created_at" key instead. See [docs/API.md#api-method-get_test_results](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/API.md#api-method-get_test_results) and [docs/API.md#api-method-get_test_history](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/API.md#api-method-get_test_history).

**Comment by pnax** [comment]
Done in #1081
