### ISSUE TITLE
Update translation to Danish, Norwegian, Finnish and Spanish (Backend)

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#1078]
For Zonemaster-Backend there is one message to be translated to Danish, Norwegian, Finnish and Spanish. You can provide the translation as a comment to this issue.

There is a new error message (BACKEND_TEST_AGENT:UNABLE_TO_FINISH_TEST) when a test times out. **Provide translation for**:
```
Zonemaster was unable to start or finish the test.
```

Done:
- [ ] Danish
- [x] Norwegian
- [x] Finnish
- [x] Spanish

**Comment by samisalmensuo** [comment]
_Zonemaster was unable to start or finish the test._
Zonemaster ei pystynyt aloittamaan tai lopettamaan testiä.

**Comment by matsduf** [comment]
Thank you, @samisalmensuo! Your translation is included in PR #1079. Please verify that is correct.

**Comment by repperille** [comment]
Zonemaster kunne ikke starte eller fullføre testen.

**Comment by matsduf** [comment]
Thanks, @repperille! I have added your translation to #1079. Please verify that is correct.

**Comment by huguei** [comment]
es: "Zonemaster no pudo iniciar o terminar la prueba."

**Comment by matsduf** [comment]
Thanks, @huguei! The translation is now in #1079 where you can verify that it is correct.

**Comment by matsduf** [comment]
Resolved by #1079, except da.

**Comment by haarbo** [comment]
da: Zonemaster var ikke i stand til at starte eller afslutte testen.
