### ISSUE TITLE
Update translation to Danish, Norwegian, Finnish and Spanish (Backend)

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#1099]
For Zonemaster-Backend there are two message to be translated to Danish, Norwegian, Finnish and Spanish. You can provide the translations as a comment to this issue.

Completely new message ID for UNABLE_TO_FINISH_TEST. **Please provide translation for**:
```
The test took too long to run (the current limit is {max_execution_time} seconds). 
Maybe there are too many name servers or the name servers are either unreachable 
or not responsive enough.
```

New tag TEST_DIED that partly takes an old message ID. **Please provide translation for**:
```
An error occured and Zonemaster could not start or finish the test.
```

Done:
- [x] Danish
- [x] Norwegian
- [x] Finnish
- [x] Spanish

**Comment by huguei** [comment]
Spanish translations.

UNABLE_TO_FINISH_TEST: "La prueba tomó demasiado tiempo en terminar (el límite máximo actual es {max_execution_time} segundos). Quizás hay demasiados servidores de nombres, o son inalcanzables, o no lo suficientemente rápidos para responder."

TEST_DIED: "Ha ocurrido un error y Zonemaster no pudo comenzar o finalizar la prueba."

**Comment by matsduf** [comment]
@huguei, please review the PO update in #1103

**Comment by samisalmensuo** [comment]
Completely new message ID for UNABLE_TO_FINISH_TEST. Please provide translation for:

Testin suorittaminen kesti liian kauan (nykyinen raja on {max_execution_time} sekuntia). 
Ehkä nimipalvelimia on liian monta, nimipalvelimiin ei saada yhteyttä, 
tai ne eivät vastaa tarpeeksi nopeasti.


New tag TEST_DIED that partly takes an old message ID. Please provide translation for:

Tapahtui virhe, eikä Zonemaster voinut aloittaa tai suorittaa testiä loppuun.

**Comment by repperille** [comment]
UNABLE_TO_FINISH_TEST: Testen tok for lang tid å kjøre (gjeldende grense er {max_execution_time} sekunder).
Kanskje er det for mange navnetjenere eller navnetjenerne er enten utilgjengelige eller ikke responsive nok.

TEST_DIED: Det oppstod en feil og Zonemaster kunne ikke starte eller fullføre testen.

**Comment by matsduf** [comment]
@repperille, please review in #1103.

**Comment by haarbo** [comment]
UNABLE_TO_FINISH_TEST:

Testen tog for lang tid at afvikle (den aktuelle grænse er {max_execution_time} sekunder).
Måske er der for mange navneservere, eller også er navneserverne enten ikke tilgængelige
eller ikke responsive nok.

TEST_DIED:

Der opstod en fejl, og Zonemaster kunne ikke starte eller afslutte testen.

**Comment by matsduf** [comment]
@haarbo, please review the Danish PO file in #1103.

**Comment by matsduf** [comment]
Resolved by #1103
