### ISSUE TITLE
Impossible to test domains where the test takes more than 5 minutes

### ISSUE THREAD

**Issue by mtoma** [zonemaster/zonemaster-backend#121]
The current backend timeout after which a process is considered dead is 5 minutes.
This stops testing of real domains where the engine takes more than 5 minutes to complete the test.
For example: with the domain "mw".
This issue needs to be fixed with care as those domains make it very easy to craft a DDOS attack on the Zonemaster website.

**Comment by mtoma** [comment]
Proposed solution: give the user a warning after a certain amount of time telling him that the test will be finished later (and will be available with the displayed test-id) and run a dedicated process completing very long tests one after the other.

**Comment by sandoche2k** [comment]
Partly relates to #96 in the engine

**Comment by sandoche2k** [comment]
@mtoma as the engine has blacklists now ... is the issue still relevant?

**Comment by pawal** [comment]
Yes, a test can still take a very long time to complete, given a good amount of name servers and IP addresses.

**Comment by sandoche2k** [comment]
@mtoma - Move this to Icebox

**Comment by sandoche2k** [comment]
@mtoma - Is this issue still relevant?

**Comment by mtoma** [comment]
Yes Sandoche, it is.
It can't be closed.

----- Original Message -----

**Comment by mattias-p** [comment]
@mtoma That requires an API change, right? Like, test_progress could return an optional message or a state value or something? Maybe the percentage should be changed to indicate the domain's progress towards the head of the queue in this new state?

**Comment by sandoche2k** [comment]
@mtoma can we close this issue ?

**Comment by matsduf** [comment]
I think there are good reasons to be able to complete tests that take long time.

**Comment by sandoche2k** [comment]
If we do not have a valid use case, then i think we should close the issue and open a new one, when we find such an use case.

**Comment by pawal** [comment]
@sandoche2k there are plenty of domains that takes a long time to test.

**Comment by sandoche2k** [comment]
@pawal @matsduf this issue has been there since 2015. There has been lots of updates in the code during this period. We need  to check if the issue still exists. If we do not find one, then close this issue and open a new issue, if we find such an issue in the future.

**Comment by sandoche2k** [comment]
@mtoma @pawal @matsduf i am closing this issue. If any point we come again with the same issue, we will create a new issue with relevant use-case.
