### ISSUE TITLE
Initialise sqlite database

### ISSUE THREAD

**Issue by aabdnn** [zonemaster/zonemaster-backend#164]
The backend supports sqlite, mysql and postgresql. However, the instructions and examples only show snippets for mysql and postgresql. Could you please also add an initialisation file for sqlite? This helps if I want to run the backend with a light workload, or for testing.

**Comment by mtoma** [comment]
Hi Anand,

The sqlite backend is mainly used for testing when the "make test" is executed.
As of now you can find a step by step procedure to run all 3 backends in the .travis.yml file in the zonemaster-backend module.

https://travis-ci.org/mtoma/zonemaster-backend

Michal

----- Original Message -----

**Comment by sandoche2k** [comment]
@mtoma Can we include them in the installation document ?

**Comment by matsduf** [comment]
Resolved by #690.
