### ISSUE TITLE
Use of uninitialized value in DB.pm

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#166]
The backend logs multiple entries of

Use of uninitialized value $test_id in numeric eq (==) at /usr/local/share/perl/5.18.2/Zonemaster/WebBackend/DB.pm line 41.
Use of uninitialized value $test_id in numeric le (<=) at /usr/local/share/perl/5.18.2/Zonemaster/WebBackend/DB.pm line 45.

**Comment by mtoma** [comment]
Hi Mats,

I don't have those warnings in the backend logs.
Can you give me a procedure to reproduce this issue please?

Michal

----- Original Message -----

**Comment by matsduf** [comment]
No, I am sorry I cannot connect the log entry to some activity. Can I increase information in logging? I do not know from where the query came and what time. As I understand it, $test_id is the "id" in the get_test_result.

When sent a get_test_result with the "id" truncated (removed last digit), then I got the following reply and log entry:

$ curl -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"get_test_results","id": "2016:0000061","params":{"language":"sv_SE.UTF-8","id":"9c751de8477b35d"}}' http://localhost:5000/ ; echo
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Querying test results with the [id] field is dissallowed by the current configuration values at /usr/local/share/perl/5.18.2/Zonemaster/WebBackend/DB.pm line 49.\n"},"id":"2016:0000061"}

Argument "9c751de8477b35d" isn't numeric in numeric le (<=) at /usr/local/share/perl/5.18.2/Zonemaster/WebBackend/DB.pm line 45.

When I sent an empty "id" I got the following:

$ curl -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"get_test_results","id": "2016:0000061","params":{"language":"sv_SE.UTF-8","id":""}}' http://localhost:5000/ ; echo
{"jsonrpc":"2.0","id":"2016:0000061","error":{"code":-32603,"message":"malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before \"(end of string)\") at /usr/local/share/perl/5.18.2/Zonemaster/WebBackend/DB/MySQL.pm line 199.\n"}}

Argument "" isn't numeric in numeric le (<=) at /usr/local/share/perl/5.18.2/Zonemaster/WebBackend/DB.pm line 45.

**Comment by mtoma** [comment]
Hmmm... Maybe it comes from the comparison to the
force_hash_id_use_in_API_starting_from_id=41359
parameter of the backend_config.ini file.

Did you set some value for this parameter in the backend_config.ini file?

----- Original Message -----

**Comment by matsduf** [comment]
I do not think I have changed anything in the ini-file, possibly set DB engine to Mysql. Here it is:

[DB]
engine=MySQL
# Next three lines are not used by the SQLite backend
user=zonemaster
password=zonemaster
database_host=localhost
# If using SQLite, database_name is the full filename for the db
database_name=zonemaster
polling_interval=0.5
#seconds

[LOG]
log_dir=logs/

[PERL]
interpreter=perl

[ZONEMASTER]
max_zonemaster_execution_time=300
number_of_professes_for_frontend_testing=20
number_of_professes_for_batch_testing=20
#seconds

[GEOLOCATION]
# Requires the Geo::IP Perl module to be installed
#maxmind_isp_db_file=

# Requires the GeoIP2::Database::Reader Perl module to be installed
#maxmind_city_db_file=

There are two backend_config.ini, and as I understand it, only the one under /etc/zonemaster/ is used. Does it mean that the one under /usr/local/share/perl/5.18.2/auto/share/dist/Zonemaster-WebBackend/ could be removed?

Is it possible to increase logging?


Yours,
Mats

--
Mats Dufberg
DNS Specialist, IIS
Mobile: +46 73 065 3899
https://www.iis.se/en/<http://www.iis.se/en>

**Comment by sandoche2k** [comment]
Close when #214 is completed

**Comment by matsduf** [comment]
Issue too old.
