### ISSUE TITLE
Incorrect SQL syntax

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#167]
The backend reports the following error in the log file:

DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL OFFSET NULL' at line 1 at /usr/local/share/perl/5.18.2/Zonemaster/WebBackend/DB/MySQL.pm line 215.

**Comment by aabdnn** [comment]
I was also just about to report this. When I want to request the backend to give me a list of the results available for some domain name, and send it this input:

```
{
"method": "get_test_history",
"params": {
    "domain": "ripe.net",
    "ipv4": "true",
    "ipv6": "true"
    }
}
```

Then I get the same error.

**Comment by mtoma** [comment]
Hi Mats and Anand,

The get_test_history API requires a limit and offset parameter. Those are optional in the PostgreSQL backend as stated in the documentation but are mandatory in the MySQL backend.
Thanks for this catch.

As a temporary workaround you can add them to the API call when MySQL is used as  a banckend.

Michal

----- Original Message -----

**Comment by matsduf** [comment]
A code patch is needed.

**Comment by matsduf** [comment]
Issue too old.
