### ISSUE TITLE
Deadlock on stopped tests

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#175]
If a test is stopped due to some error (e.g. truncated IPv4 address accepted by validate_syntax(); see issue #173) then the progress, test_progress(), of that test will stop at 1%. There is no error returned in test_progress(), and the error that is returned by get_test_result() is identical to the error that you will get if a test has not yet been completed.

It should be possible to distinguish between a test that is in progress and a test that has been stopped due to some error.

**Comment by sandoche2k** [comment]
@matsduf do we still have this issue ?

**Comment by matsduf** [comment]
This issue has not been solved.

**Comment by matsduf** [comment]
Create a new issue for having garbage collector.

**Comment by matsduf** [comment]
There is a new issue #525 that replaces this.
