### ISSUE TITLE
Report IP addresses used as source for testing

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#203]
Make it possible for the GUI (and other interfaces) to report the source addresses that the backend uses for the tests. This would require an update to the API to let that information go back to the calling client.

**Comment by mtoma** [comment]
I'm not sure which IP addressee are you speaking about. The IP of the machine the backend is running on?

**Comment by matsduf** [comment]
I am referring to the addresses that are source address of the DNS queries. It could be a subset of the addresses that machine is configured with, and in some cases, another address as a result of NAT. By default, if the machine has one global scope IPv6 address and one public IPv4 address, assume those. It must be configurable to set addresses. Maybe it should be possible to turn it off, or that could be done in the GUI.

The reasoning behind it is that if you see that Zonemaster cannot reach your nameserver it is valuable to know from what IP does Zonemaster test.

**Comment by mtoma** [comment]
Ok, I see now. 
Not sure if this is an iformation that is easy to get at the application level.
Consider the current setting of the Zonemaster webserver which runs the DNS tests as well.
It uses the afnic resolvers which it reaches through an internal routing scheme those than query the target domain. Si in this particular case the backend has now way to get the public IP address of the server that will issue the DNS queries without hardcoding them in some config file.
It could of course "guess" that information if the resolvers were on the same machine as the backend assuming that that the DNS queries are going to be issued with the same public IP address as HTTP requests and query some kind of "Get My IP address" HTTP server but it seems to me rather fragile.
I think that the only real solution here is to setup some kind of "get my IP address custom DNS server" and get the public IP address of the DNS queries using the DNS protocol itself.
This seems to me much more complex than just add an API to the backend no?

**Comment by pamasse** [comment]
@vlevigneron Could you help us to find a solution ? 
Does zonemaster-engine uses the resolv.conf of the OS ? Or it only uses its own resolver ? 

Could we use something like "dig -t a whoami.v4.powerdns.org" in order to get the public ip ?

**Comment by matsduf** [comment]
In general, Zonemaster emits the queries itself directly to the targets.

It is hard to know how this should be done. The Test Agent might be running on a different server from the RPC API.

**Comment by matsduf** [comment]
@pamasse, I do not think we should prioritize this issue now. It is too complex.

**Comment by matsduf** [comment]
Too complex.
