### ISSUE TITLE
Timeout should conclude a test

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#216]
If a test ends due to timeout (see #207) the backend should conclude that test so that progress is set to 100 and the result contains an error message.

**Comment by mtoma** [comment]
The zonemaster engine has no such error as a "timeout". The tests must all finish or else there is a bug in the engine.

**Comment by matsduf** [comment]
I am not refering to the engine, I am refering to the backend. For #207 @mtoma said "This means the tests took more than 5 minutes and were considered as impossible to finish by the backend process." Isn't that a timeout?

**Comment by mtoma** [comment]
No, not really. This is an arbitrary time chosen by the backend before killing the testing process.
This was implemented as a workaround back in time when we had the engine hanging indefinitely on some domains. This had as a consequence that the users were retrying with another test request of the same domain through the web GUI locking all the backing resources in a few requests.

We should probably agree on some kind of maximum testing time before considering the engine has a bug. It seems the current 5 minutes are too low for certain domains.

**Comment by mtoma** [comment]
And probably add a parameter of this timeout as it will depend on many external conditions.

**Comment by matsduf** [comment]
@mtoma, your description ("This is an arbitrary time chosen by the backend before killing the testing process") is what I call timeout. We give up after a certain time.

1. I agree that we should agree on the maximum testing time. I think five minutes could be fine, but ten is also fine. Probably better to have the longer time. Or maybe have that in the configuration file with a default of, say, ten minutes.
2. When the backend gives up ("timeout") it must consider progress to be 100 and add some error message. If I create a batch it must always complete.

**Comment by mtoma** [comment]
Yes, this can be done. But I think the backend should be as transparent as possible towards the engine.
Having the backend decide a test will not complete while the engine basically says it just needs more time doesn't seem ok to me.
But we could certainly artificially generate a critical system message for this case.
The implementation will not be simple as the only reasonable way to handle this case would be to catch the KILL signal.
If I'm the only one to work on the backend issues it is not realistic to have it for the 2016.2 release.

**Comment by matsduf** [comment]
If I understand you, @mtoma,  correctly, there is a timeout in the backend today. I think it is fine to keep it for now, but there must be an error message and the progress must be set to 100. If you create a batch there should not be some tests (TLDs) that are never completed.

**Comment by mtoma** [comment]
The process is now killed with a "kill -9" signal. It must be cough and an error generated and saved to the database in a format matching the engine SYSTEM type messages.

**Comment by matsduf** [comment]
> The process is now killed with a "kill -9" signal. It must be cough and an error generated and saved to the database in a format matching the engine SYSTEM type messages.

Yes, that looks fine. Today the timeout is 5 minutes, isn't it? I suggest extending it to 10 minutes. 

Is catching the 'kill' straight forward or complex?

Suggestion for message:

```
    {
      "message": "The test could not be completed in the given test window.\n",
      "module": "BACKEND",
      "level": "CRITICAL"
    }
```

Since we have translation, will it work to create a new module not used by the Engine.

**Comment by mtoma** [comment]
No catching the kill signal is not that complex. But the engine is now in charge of all the translation so this message should somehow be added to the engine or else I need to better understand the current translation system to see if the backend could use the same system to translate custom messages.

**Comment by sandoche2k** [comment]
@matsduf @mtoma As i understand if the timeout is increased to 10, this issue can be closed. For the translation, please add another issue.

**Comment by matsduf** [comment]
> @matsduf @mtoma As i understand if the timeout is increased to 10, this issue can be closed. For the translation, please add another issue.

No, a longer timeout is not enough. A timeout is necessary, and when it is executed the test must be completed so that progress is set to 100. What we need to solve this issue is:

1. A defined timeout.
2. Catching the timeout and setting progress to 100.
3. Adding a message.
4. Incorporating the message.

At the time being, 1-3 are most important. We could create a separate issue for 4 to solve later.

**Comment by sandoche2k** [comment]
I am moving it to 2017.2. Needs discussion.

**Comment by sandoche2k** [comment]
Is this still a valid issue?

**Comment by matsduf** [comment]
Since it has not been resolved it is still valid. If Zonemaster gives up testing a domain the test must till be considered to be finished, but with error.

**Comment by sandoche2k** [comment]
@mattias-p or @mtoma can you take owner of this issue and inform whether this issue could be solved by 2019.2?

**Comment by matsduf** [comment]
Create a new issue for having garbage collector. Also see #175

**Comment by matsduf** [comment]
There is a new issue #525 that replaces this.
