### ISSUE TITLE
Feature request: avoid "progress" update for batch tests

### ISSUE THREAD

**Issue by aabdnn** [zonemaster/zonemaster-backend#274]
Batch tests are not normally submitted by interactive clients (such as the GUI), and as such, have no need for a progress meter. In fact, when you submit domains in a batch, there is no way, as far as I can see, to get the progress of an individual test of the batch.

Can the wbdaemon be modified so that it doesn't bother updating the "progress" column of the database while running? It should only change progress from 0 to 1 at the start of the test, and then to 100 at completion. This avoids extra unnecessary writes to the database.

**Comment by pnax** [comment]
Addressed by #944.
However note the following side effect. When running batches and single tests on the same instance, single tests won't have their progress updated if they are reusing tests created in a batch, see #979.
