### ISSUE TITLE
Complete specification of API input parameter formats

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#317]
### Purpose and scope

The purpose of this issue is to document the status quo and introduce reasonable constraints where appropriate. Major changes to the API such renaming or moving parts of parameter structures should not be included in this issue.

### Requirements

- [x] Every parameter of every method must be described with name and data type. If the method accepts a single scalar value as its parameter, specifying the data type is sufficient for the purpose of this issue. (#320)
- [x] Every data type with the basic data type `array` must specify the data type of the elements. (we don't have any of these)
- [x] Every data type with the basic data type `object` must specify all its keys with name and value data type.
- [x] Every data type must be fully specified with basic data type and additional restrictions (e.g. regular expression).
- [x] Every parameter and object property value must be declared to be either optional or required.
- [x] Every optional parameter and object property value must declare its default value.

**Comment by pamasse** [comment]
@mattias-p I checked some checkbox based on the pr #320

**Comment by sandoche2k** [comment]
@pamasse and @mattias-p Please focus on completing the specification.

**Comment by sandoche2k** [comment]
user_ip, location data type, user_location_info deprecated conforming to GDPR requirements in release 2018.1. Delete these parameters in the backend, if they are already present.

**Comment by pamasse** [comment]
I think this request is too strict :  "Every optional parameter and object property value must declare its default value." 
Some optional don't have default value. 
For instance, we don't have default value for "ds_info" or "nameservers".

**Comment by pamasse** [comment]
We need to add some restriction on Domain name and Username data types.

**Comment by sandoche2k** [comment]
@mattias-p @pamasse close?

**Comment by sandoche2k** [comment]
@mattias-p update with the missing information

**Comment by mattias-p** [comment]
Three more things remain before we can check the two bottom boxes:
1. *DS Info* does not specify default values for its optional properties.
2. The `"frontend_params"` parameter of the *get_frontend_params* method is neither required nor optional.
3. The `"test_params"` parameter of the *add_batch_job* method is neither required nor optional.

**Comment by sandoche2k** [comment]
@mattias-p if completed we could close this issue and create specific issues for any missing input parameters
