### ISSUE TITLE
The API method get_test_history() must require domain

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#333]
The API method get_test_history() must require domain to be non-empty in the call. Unless it should return an error.

**Comment by sandoche2k** [comment]
Deprecate the possibility of having an empty domain name parameter

**Comment by pamasse** [comment]
The API Documentation already restrict the possible value of domain name : 

### Domain name
Basic data type: string
1. If the string is a single character, that character must be `.`.
2. The length of the string must not be greater than 254 characters.
3. When the string is split at `.` characters (after IDNA conversion,
   if needed), each component part must be at most 63 characters long.

To fix this issue, i will add a comment in the documentation which recommend to update the GUI and allow empty domain in the backend validation layer.

**Comment by matsduf** [comment]
The document is good, the implementation still has a quirk for empty domain names to handle a bug in the old GUI.

**Comment by mattias-p** [comment]
We could add an item about the empty string, stating that it's allowed but deprecated.

**Comment by sandoche2k** [comment]
@pamasse closed?

**Comment by matsduf** [comment]
It has been implemented.
