### ISSUE TITLE
Translation on FreeBSD 11

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#353]
Selecting language does not work in FreeBSD 11. There is currently no work-around. See also issues dotse/zonemaster-cli#46 and dotse/zonemaster-cli#64.

On FreeBSD the `language` parameter of the `get_test_results` method is ignored. Instead the translation language is determined from the `LC_ALL`, `LC_MESSAGES` and `LANG` environment variables when the service is started.

**Edit:** Updated links to the correct issues.
**Edit:** Clarified version of FreeBSD.

**Comment by matsduf** [comment]
Also see #350

**Comment by mattias-p** [comment]
Partially fixed by #526. #530 was created for the remaining problem.
