### ISSUE TITLE
Installation hick-ups

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#360]
I noticed a few hick-ups in the installation procedure.

Debian 7:
* zm-backend.sh status command gives no output

CentOS 7:
* ~Engine CPAN dependencies installation failed - I did manage to install all the dependencies separately by splitting up the cpan command~ (cannot reproduce anymore)
* A unit test failed for Zonemaster::LDNS: In t/wireformat.t the TLSA test
* The `mysql` command prompts for a password
* zm-centos.sh status command gives no output

**Comment by mattias-p** [comment]
@matsduf replied:

> Debian 7: zm-backend.sh status command gives no output

Yes. I have seen that before. Not a major issue and since Debian 7 soon is outdated we should not try to fix.

> CentOS 7: Engine CPAN dependencies installation failed - I did manage to install all the dependencies separately by splitting up the cpan command

I did not see that. No issue when I installed today.

> CentOS 7: A unit test failed for Zonemaster::LDNS: In t/wireformat.t the TLSA test

I did not see that. No issue when I installed today.

> CentOS 7: The mysql command prompts for a password

Yes, but is that an issue?

> CentOS 7: zm-centos.sh status command gives no output

Yes. I have seen that before. Not a major issue, but we should consider fixing that for next release.

**Comment by mattias-p** [comment]
Status commands: The silent status commands add more to the confusion than they detract. As such I think they should be removed from the installation instruction until they're actually useful.

CPAN installation: The CPAN installation failure seems a bit weird. Maybe it's something on CPAN that's chnaged. Will check again.

Password prompt: I believe the password prompt can be bypassed by just omitting the `--password` option. When you install mysql you get an empty root password by default. I think it's reasonable to assume that people who have changed that are also competent to add the `--password` argument on their own accord.

**Comment by mattias-p** [comment]
CPAN installation: I restored a snapshot from just before the command and ran the same `cpan` command, this time it worked. Maybe someone uploaded something broken to CPAN and I happened to catch it before it was fixed?

**Comment by mattias-p** [comment]
The unit test failure is reproducible though. I get a segfault on line 62 of t/wireformat.t in Zonemaster::LDNS on CentOS 7.

**Comment by matsduf** [comment]
I cannot reproduce the issue on CentOS. Below is run from a distfile made from the updated develop branch on CentOS. I ran a full test with TEST_WITH_NETWORK=1.

```
$ TEST_WITH_NETWORK=1 make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t
t/axfr.t ........... ok   
t/dnssec.t ......... ok    
t/idn.t ............ ok   
t/load_zonefile.t .. ok   
t/netldns.t ........ ok    
t/packet.t ......... ok    
t/regression.t ..... ok   
t/resolver.t ....... ok    
t/rr.t ............. ok    
t/rrlist.t ......... ok    
t/serialize.t ...... ok   
t/threads.t ........ ok   
t/utils.t .......... ok   
t/wireformat.t ..... ok    
All tests successful.
Files=14, Tests=248, 17 wallclock secs ( 0.07 usr  0.02 sys +  0.92 cusr  0.17 csys =  1.18 CPU)
Result: PASS
```

**Comment by JohanIIS** [comment]
> zm-backend.sh status command gives no output

In relation to this, I also noticed this happening in Ubuntu 14 but not 16 and 18. There is also a difference in behavior for the _zm-backend.sh start_ command. In 14, it yields immediate output ("[Started]" or similar), but in 16 and 18 it displays nothing. If the issue with _status_ in 14 is not to be fixed, I think it'd be ideal if the _start_ behavior in 16 and 18 could match 14, especially if the current proposal is the removal of the _status_ command from instructions.

**Comment by pnax** [comment]
Installation document has evolved a lot since this issue has been opened and from what I see the errors listed here have been solved.
