### ISSUE TITLE
Installation of new dependencies

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#423]
JSON::Validator and Try::Tiny (or preferably their OS packages) should be added to the installation instruction.

**Comment by sandoche2k** [comment]
@mattias-p for which OS?

**Comment by mattias-p** [comment]
All of them. JSON::Validator and Try::Tiny are both listed in Makefile.PL, but none of the are listed in Installation.md.

**Comment by mattias-p** [comment]
@sandoche2k It works because we have transitive dependencies to them as well as direct dependencies.

We should definitely keep all direct dependencies in Makefile.PL. Otherwise if our dependencies switch out their dependencies for whatever reason, installing Engine from CPAN will stop working all of a sudden.

We should list all direct dependencies in the installation instruction for analogous reasons.

**Comment by mattias-p** [comment]
This was done long ago.
