### ISSUE TITLE
Switch to MariaDB

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#434]
Today all our installation instructions use MySQL. In some cases we're taking installation files from third party repositories. After dropping support for Debian 7, all our supported OS versions ship with MariaDB. We should start using MariaDB instead of MySQL for all our installation instructions.

- [x] CentOS (#663)
- [x] Debian/Ubuntu (#564)
- [ ] FreeBSD (does not work on FreeBSD #664)

**Comment by matsduf** [comment]
OK from F2F.

**Comment by matsduf** [comment]
@mattias-p, is there anything preventing this to be implemented with v2020.1?

**Comment by mattias-p** [comment]
Not that I know of.

**Comment by matsduf** [comment]
This issue will be resolved by updating the supported database versions in the main (Zonemaster/Zonemaster) README (see zonemaster/zonemaster/pull/890) and by updating the installation instructions.

**Comment by sandoche2k** [comment]
@matsduf if the install instructions for FreeBSD is also added for MariaDB, we can close this issue

**Comment by matsduf** [comment]
> @matsduf if the install instructions for FreeBSD is also added for MariaDB, we can close this issue

I will fix that.

**Comment by matsduf** [comment]
Zonemaster-Backend requires `DBD::mysql` but that cannot be installed together with MariaDB in FreeBSD (using FreeBSD packages). At least for this release MySQL is kept for FreeBSD.

@mattias-p and @sandoche2k, should this be closed and some new ticket be created?

**Comment by sandoche2k** [comment]
+1

**Comment by mattias-p** [comment]
I added a task for each OS to the issue description and added links to the PR where they were resolved.

**Comment by matsduf** [comment]
> I added a task for each OS to the issue description and added links to the PR where they were resolved.

I created a separate issue for FreeBSD and updated the issue description. Is that how you want it?

**Comment by mattias-p** [comment]
> I created a separate issue for FreeBSD and updated the issue description. Is that how you want it?

My idea was to use a task list to track what OSes are done migrating to MariaDB.

**Comment by matsduf** [comment]
> My idea was to use a task list to track what OSes are done migrating to MariaDB.

I removed the tick for FreeBSD. Can we close this issue?

**Comment by sandoche2k** [comment]
+1

**Comment by matsduf** [comment]
We moved to MariaDB on all OSs except FreeBSD, which it is not supported in our setup. An issue for FreeBSD has been created, #664. We can now close this issue.
