### ISSUE TITLE
Replace Github service Travis

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#444]
Github services are deprecated. The repo uses Github service to get the Travis function. We need to update before the end-date.

https://developer.github.com/changes/2018-04-25-github-services-deprecation/
https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

**Comment by matsduf** [comment]
Now the Github service Travis has stopped working.

**Comment by matsduf** [comment]
@sandoche2k, I have not read deep enough to understand what we have to do. I still see no trace of Travis.

**Comment by sandoche2k** [comment]
Did you authorize for travis-ci.com?

**Comment by matsduf** [comment]
Why don't we see any traces of Travis in #460?

**Comment by sandoche2k** [comment]
@mtoma as indicated for other components... can you check whether we need to replace travis

**Comment by matsduf** [comment]
Travis is still working.
