### ISSUE TITLE
Profiles error 

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-backend#473]
In the file : /var/log/zonemaster/zonemaster_backend_testagent.log, i get the following error:

```
2019-01-23T13:51:26Z [11682] CRITICAL - The profile [example_profile_1] is not defined in the backend_config ini file at /usr/local/share/perl/5.20.2/Zonemaster/Backend/TestAgent.pm line 151.
2019-01-23T13:51:26Z [11682] NOTICE - Daemon terminating
```
the backend_config.ini is as follows:

```
[...]
[PUBLIC PROFILES]
# example_profile_1=/home/sandoche/test_profile.json
# default=/home/sandoche/profile.json

[PRIVATE PROFILES]
# example_profile_2=/example/directory/test2_profile.json
```

**Comment by sandoche2k** [comment]
I got to say, i am not able to recreate the same error, with the same configuration in backend_config.ini

**Comment by mtoma** [comment]
Can you explain what was the expected result Sandoche?
It says example_profile_1 is not defined and as it is commented out in the backend_config.ini it is indeed not defined.
So if I look only at the provided information in the issue I would say I don't see anything wrong.

**Comment by sandoche2k** [comment]
I was expecting that example_profile_1 is commented, the code does not check it. Hence, do not emit an error. 

But, the interesting thing is that, when i recreated the same scenario again, i do not have an error.

**Comment by mtoma** [comment]
Hmmm... Ok, I see. My bad, you are right. That definitely is strange.
Tell me if you reproduce this issue on a VM and I'll debug it directly there.
