### ISSUE TITLE
CRITICAL - Memory leak of the test_agent module

### ISSUE THREAD

**Issue by mtoma** [zonemaster/zonemaster-backend#481]
The zonemaster test agent crashes on a regular basis with out of memory error:
2019-01-29T15:32:17Z [78459] CRITICAL - Cannot fork: Cannot allocate memory at /usr/local/share/perl5/Parallel/ForkManager.pm line 52.
2019-01-29T15:32:17Z [78459] NOTICE - Daemon terminating

This is very likely a memory leak either in the backend or in the engine.

**Comment by mtoma** [comment]
The process is eating memory (should be heap) very quickly. This is the output of a pmap command on the process every minute:

grep 0000000004e23000 pmap_out.txt 
0000000004e23000  11496K rw---   [ anon ]
0000000004e23000  14556K rw---   [ anon ]
0000000004e23000  14680K rw---   [ anon ]
0000000004e23000  16152K rw---   [ anon ]
0000000004e23000  16516K rw---   [ anon ]
0000000004e23000  16760K rw---   [ anon ]

**Comment by sandoche2k** [comment]
Is the problem relating to the engine?

**Comment by mtoma** [comment]
Not sure. It might be. As of now I would say 70% chance backend code and 30% chance engine code.
But it is extremely difficult to debug.

**Comment by matsduf** [comment]
PR #482 is assumed to fix this issue, but it has not been verified that it does solve the issue.

**Comment by sandoche2k** [comment]
Machine 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"

**Comment by mtoma** [comment]
We need an easy way to reproduce the issue.
@mtoma will work on a method to reproduce this issue

**Comment by sandoche2k** [comment]
I have sent you information on connecting to the test machine

**Comment by mtoma** [comment]
to reproduce the pmap output:
1. Find the pid of the zonemaster_test_agent process
2. As root run: pmap $PID
3. The output will start like this:
0000000000400000      8K r-x-- perl
0000000000601000      4K r---- perl
0000000000602000      4K rw--- perl
0000000001423000  45988K rw---   [ anon ]
000000000410c000 186872K rw---   [ anon ]
00007fe433ce9000     32K r-x-- libnss_sss.so.2
00007fe433cf1000   2044K ----- libnss_sss.so.2
00007fe433ef0000      4K r---- libnss_sss.so.2
00007fe433ef1000      4K rw--- libnss_sss.so.2

4. the second [anon] region grows over time
000000000410c000 186872K rw---   [ anon ]

5. Monitor this line over a period of about an hour to get the results described in the first comment

**Comment by mattias-p** [comment]
Here's a slightly more cut'n'paste friendly one-liner:
```sh
sudo pmap $(pgrep -f zonemaster_backend_testagent) | grep anon
```

**Comment by mtoma** [comment]
The issue is impossible to reproduce on a clean ZM install (centos 7)

**Comment by sandoche2k** [comment]
If it is the same for PostgreSQL, i think we should go for a clean install on zonemaster.fr. What is your opinion @mtoma?

**Comment by matsduf** [comment]
Is it possible to take a snapshot of zonemaster.fr or zonemaster to be able to try to investigate in an development environment? It is still interesting to understand the cause of the problem.

**Comment by mattias-p** [comment]
@mtoma Have you learned anything about what the leaked memory consists of?

**Comment by mtoma** [comment]
The bug is reproduced. I wasn't expecting PostgreSQL to play any specific role but it in fact is.
Here is the command-line that reproduces the issue with quick decrease in free memory:

```
for i in {1..300000}; do curl -s -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"start_domain_test","id":"1", "params":{"domain":"domainE-'$i'"}}' http://localhost:5000/ && echo; curl -s -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"start_domain_test","id":"1", "params":{"domain":"domainD-'$i'"}}' http://localhost:5000/ && echo; curl -s -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"start_domain_test","id":"1", "params":{"domain":"domainC-'$i'"}}' http://localhost:5000/ && echo; curl -s -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"start_domain_test","id":"1", "params":{"domain":"domainB-'$i'"}}' http://localhost:5000/ && echo; curl -s -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"start_domain_test","id":"1", "params":{"domain":"domainA-'$i'"}}' http://localhost:5000/ && echo; sleep 60; free; done
```

**Comment by matsduf** [comment]
Good work. Let us see if you can find a solution too.

**Comment by mtoma** [comment]
Seems much more feasible now. Yes I'll fix this.

**Comment by mtoma** [comment]
Colsed with pull request #488
