### ISSUE TITLE
Long descriptions of TAGs

### ISSUE THREAD

**Issue by godzone** [zonemaster/zonemaster-backend#506]
Is there somewhere I can lookup and return to my user a longer description associated with each TAG e.g. NAMESERVER_HAS_TCP_53 => 'The name server did not respond to DNS queries over TCP port 53' or similar.

I am accessing the zonemaster:test_results table directly and it doesn't have a suitable description.

**Comment by sandoche2k** [comment]
https://github.com/zonemaster/zonemaster-engine/blob/master/share/en.po

**Comment by godzone** [comment]
> On 13/05/2019, at 7:52 PM, sandoche2k <notifications@github.com> wrote:
> 
> https://github.com/zonemaster/zonemaster-engine/blob/master/share/en.po <https://github.com/zonemaster/zonemaster-engine/blob/master/share/en.po>
> 

Thank you.

**Comment by matsduf** [comment]
Can this be closed?

**Comment by godzone** [comment]
Yes, thanks.
