### ISSUE TITLE
Warning message from RPCAPI

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#507]
Read in the zm_rpcapi.log file:

```
2019/05/16-21:38:09 Starman::Server (type Net::Server::PreFork) starting! pid(26464)
Binding to TCP port 5000 on host 127.0.0.1 with IPv4
coerce(1) will be deprecated. at /usr/local/lib/perl5/site_perl/JSON/Validator/Joi.pm line 84.
```

coerce(1) should be reviewed.

**Comment by matsduf** [comment]
Find the recommended replacement solution.

**Comment by mattias-p** [comment]
@mtoma Sorry I nicked this issue from you. I didn't realize you were the assignee until now. I guess I should have paid more attention and I hope you didn't start working on it. Assigning myself since I already got the fix accepted upstream and I already made the PR for the workaround.

**Comment by mattias-p** [comment]
@matsduf Shouldn't this be closed as fixed?

**Comment by matsduf** [comment]
Since this is just a work-around so we agreed to keep this issue, but for me it is OK to close it. Should an issue to remove the work-around, when possible, be created?

**Comment by matsduf** [comment]
See #562.
