### ISSUE TITLE
Backend not starting after reboot on Debian

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#513]
Both daemons (RPCAPI and Agent) start just fine when following the instruction on Debian, but when you reboot the machine they aren't automatically started, despite the `sudo update-rc.d zm-backend.sh defaults` command. Presumably this is because Debian has switched to systemd, and we haven't adapted.

**Comment by matsduf** [comment]
I assume we can wait until v2019.2 with this.
