### ISSUE TITLE
Can't locate object method "profile" via package "Zonemaster::Engine"

### ISSUE THREAD

**Issue by eserte** [zonemaster/zonemaster-backend#516]
The test suite fails on some of my smokers:
```
Can't locate object method "profile" via package "Zonemaster::Engine" at t/test01.t line 13.
t/test01.t ................ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
```
This seems to happen if an older version of Zonemaster::Engine is installed. Statistical analysis:
```
****************************************************************
Regression 'mod:Zonemaster::Engine'
****************************************************************
Name           	       Theta	      StdErr	 T-stat
[0='const']    	      0.0000	      0.0000	   0.00
[1='eq_v2.0.6']	      0.0000	      0.0000	   0.00
[2='eq_v2.0.7']	      0.0000	      0.0000	   0.00
[3='eq_v3.0.3']	      1.0000	      0.0000	60652135482366088.00

R^2= 1.000, N= 88, K= 4
****************************************************************
```

**Comment by matsduf** [comment]
Zonemaster-Backend version v3.0.0 or higher requires Zonemaster-Engine version v3.0.0 or higher as documented in the release notes. It was a breaking change when "profile" replaced old "policy" and "config".

Please upgrade all parts of Zonemaster.

If this does not answer your issue, please reopen this issue.

**Comment by eserte** [comment]
@matsduf: Required minimum versions should be specified in Makefile.PL or similar files, so CPAN.pm and other installers can automatically upgrade if necessary.

Reopening issues is not possible in github, at least for the requestor.

**Comment by matsduf** [comment]
@eserte, thank you. Please see #518.

**Comment by matsduf** [comment]
@eserte, we have now resolved the issue. We have updated Makefile.PL as you suggested and created new packages on CPAN. See [v2019.1.1] release notes (Zonemaster) which also links to the Zonemaster-Backend [v4.0.1] release notes.

Thanks again.

[v2019.1.1]: https://github.com/zonemaster/zonemaster/releases/tag/v2019.1.1 
[v4.0.1]: https://github.com/zonemaster/zonemaster-backend/releases/tag/v4.0.1
