### ISSUE TITLE
Document the DB section in backend_config.ini

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#520]
We've started documenting the various configuration options of Backend but it's not complete.
This issue is limited to filling in the details of the DB section.

In the PR for issue #496 we should be able to add a line documenting the new configuration property.

**Comment by mattias-p** [comment]
The documentation of valid values for the `DB.engine` property should clarify that `MySQL` is a valid value for MariaDB.

**Comment by matsduf** [comment]
Resolved by #730.
