### ISSUE TITLE
Should required version be set in the code?

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#523]
Version v4.0.x of Zonemaster::Backend requires at least version v3.0.0 of Zonemaster::Engine and at least version v2.0.0 of Zonemaster::LDNS, but that is not stated in the code (RPCAPI.pm and TestAgent.pm). They accepts any version. Wouldn't it be better to state it in them to get a meaningful error message if wrong version is installed?

**Comment by mattias-p** [comment]
I think the answer to this is no. I fail to come up with any real benefits over having just the installation-time checks. On the other hand I see a number of harms: greater burden of maintenance, greater risk of botched releases and greater burden of testing.

**Comment by matsduf** [comment]
I feel that you exaggerate the down sides. Yes, there will be yet another place to update the dependency, but that is at the same spot as we already update the version of the Perl module itself. The other "harms", risk of bothced releases and greater burden of testing, I see as non-existing.
