### ISSUE TITLE
Garbage collector for unfinished tests

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#525]
A test is created in the database by RPCAPI and then processed (executed) by TestAgent. Until a TestAgent has set "progress" to 100 (%) RPCAPI will not present the result of that test.

If the TestAgent does a timeout or crashes on a test, the "progress" will never go to 100, which means that the test will never be visible from the RPCAPI. Especially for batches this is a problem, but also for a single test this is a problem because it is never completed.

* Some kind of garbage collector is needed that can make a test, that has not completed within some set time, finished (progress = 100). Or it could be a new status that is set to "done".
* The timeout time that the garbage collector should use must be configurable in the backend.ini.
* When the garbage collector makes a test finished it should also add a system message that says that the test was never finalized. It could be message in SYSTEM with a default level of CRITICAL.
* The RPCAPI must present tests that have been finished in this way. 

This issue is related to #175 and #216.

**Comment by sandoche2k** [comment]
@mtoma to have a look

**Comment by matsduf** [comment]
Resolved by #544.

**Comment by mtoma** [comment]
What is blocking this issue from being merged again?
