### ISSUE TITLE
Translation language gets stuck on FreeBSD 11

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#530]
Selecting language does not work correctly on FreeBSD 11. After you start the RPCAPI and call `get_test_results` with a translation language argument, the result is correctly translated to that language. However, if you keep making those calls the translation language argument is no longer respected. Instead translations get stuck on the language from a previous call. Curiously, it doesn't get stuck on the language requested in the first call, but on the one requested in the second call.

#526 partially fixed #353 and #512. This issue covers the remaining problem.

**Comment by matsduf** [comment]
The issue is still there for FreeBSD 11.3.

**Comment by mattias-p** [comment]
I can't reproduce this. I believe it's been fixed in the Engine develop branch.

Can we close this?

**Comment by matsduf** [comment]
Yes, if it has been resolved it should be closed. If you are not sure I can run a test.
