### ISSUE TITLE
TestAgent: Graceful shutdown

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#532]
Today it's not possible to shut down the Test Agent gracefully. Having this ability is desirable during reconfiguration and software updates.

The Test Agent should switch over to a new state on SIGTERM. No new workers should be started in this state, but existing ones should be allowed to finish as usual. When no workers exist, the master process should exit.

This issue was created as a follow-up to #528. That issue suggests reloading the configuration on SIGHUP, but graceful shutdown is more useful.

**Comment by matsduf** [comment]
Resolved by #533.
