### ISSUE TITLE
Install zmb and zmtest by default

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#536]
Having `zmb` and `zmtest` installed by default makes functional testing of Backen more convenient.

At the time of writing `zmb` and `zmtest` are deemed experimental. While they're deemed experimental they should not be installed in any directories commonly included in $PATH.

**Comment by matsduf** [comment]
This issue is based on a change request I made in PR #534. I requested that they are installed by default, but not necessarily in some directory in $PATH. It would be convenient to have the scripts available when we are doing testing before release.
