### ISSUE TITLE
Demonstrate that garbage collection of unfinished tests works in a unit test

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#546]
Procedure:
1. Create a new test. (using the same DB call as `start_domain_test`)
2. Start the test. (using the same DB call as `TestAgent`)
3. Run the garbage collector.
4. Verify that the test is still active with no result. (using the same calls as `get_test_progress` and `get_test_results`)
5. Make time pass, an amount of less than `timeout_before_retrying_test_in_minutes`.
6. Run the garbage collector.
7. Verify that the test is still active with no result.
8. Make time pass, an amount of totaling at more than `timeout_before_retrying_test_in_minutes`.
9. Run the garbage collector.
10. Verify that the test is finalized with a critical error.

Requirements:
* The passing of time should not be real, but rather only apparent to the garbage collector.
* The unit test should use the real DB module with a mock database adapter.

**Comment by matsduf** [comment]
This issue is connected to PR #525. This issue should preferably be fixed in the same release as the PR.

**Comment by mattias-p** [comment]
The "make time pass" step would be implemented using the mechanism described in #758.
