### ISSUE TITLE
Update installation instructions for Backend for CentOS 8

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#548]
CentOS 8 is a new OS planned to be supported by release v2019.2. The installation instructions probably need to be adjusted for CentOS 8. There could be more binary packages available, but there could also be other changes.

CentOS 8 uses MySQL 8, which is new to Zonemaster, and PostgreSQL 9.6, which is already by for Debian 9.

**Comment by sandoche2k** [comment]
Fixed by https://github.com/zonemaster/zonemaster-backend/pull/604
