### ISSUE TITLE
Update installation instructions for Backend for Debian 10

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#549]
Debian 10 is a new OS planned to be supported by release v2019.2. The installation instructions probably need to be adjusted for Debian 10. There could be more binary packages available, but there could also be other changes.

Debian 10 uses PostgreSQL 11.5, which is new to Zonemaster, and MariaDB 10.3 (10.1 is used for Debian 9).

**Comment by matsduf** [comment]
Resolved by PR #564

**Comment by mattias-p** [comment]
Fixed by #564.
