### ISSUE TITLE
Re-enable Perl 5.16 in Travis

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#551]
#541 breaks Travis for Perl 5.16. Instead of postponing #541 (and zonemaster/zonemaster-ldns#85) until the next release we disable Perl 5.16 in Travis as part of #541. 

Perl 5.16 must be re-enabled in Travis.

**Comment by sandoche2k** [comment]
@matsduf who is assigned to this issue?

**Comment by matsduf** [comment]
@mattias-p, can you resolve this issue?

**Comment by mattias-p** [comment]
I'll take a look.

**Comment by matsduf** [comment]
Will be resolved by #645.
