### ISSUE TITLE
Warning from zm-backend.sh

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#557]
I'm getting warning that says `Variable "$caught_sigterm" will not stay shared` in the systemd log when running
```
sudo service zm-backend.sh start
sudo service zm-backend.sh status
```

The warning is technically correct. It is raised because `catch_sigterm` is mistakenly declared as a proper sub (inside `main`) but refers to a local variable declared in `main`. Declaring `catch_sigterm` as a closure will fix the warning.

`catch_sigterm` is never called outside of `main`, so there's no risk for bad behavior because of this. Nevertheless the warning should be fixed.

**Comment by matsduf** [comment]
Resolved by #563.
