### ISSUE TITLE
UTF-8 issue for idn domain names

### ISSUE THREAD

**Issue by mtoma** [zonemaster/zonemaster-backend#570]
The answer for an idn domain name like café.fr comes back from the backend with a double utf8 encoding.

**Comment by matsduf** [comment]
PR #571 has been created to resolve the issue.

**Comment by mtoma** [comment]
More detailed explanation of the issue for example here: https://www.endpoint.com/blog/2014/02/19/dbdpg-utf-8-perl-postgresql

**Comment by mattias-p** [comment]
For the record, we currently need to support the following package versions:
* DBD-Pg 2.19 on CentOS 7
* DBD-Pg 3.5.3 on Ubuntu 16.04 and Debian Stretch
* DBD-Pg 3.7.0 on Ubuntu 18.04
* DBD-Pg 3.7.4 on CentOS 8 and Debian Buster
* DBD-Pg 3.10.4 on FreeBSD

**Comment by sandoche2k** [comment]
@mtoma can you close ?

**Comment by matsduf** [comment]
Fixed by #571.
