### ISSUE TITLE
Initialize database in Postgres creates a postgres user instead of zonemaster user

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-backend#575]
Normally the database user should be zonemaster?
```
[centos@ip-172-31-28-37 Zonemaster-Backend]$ sudo -u postgres psql -f ./initial-postgres.sql
CREATE ROLE
CREATE DATABASE
You are now connected to database "zonemaster" as user "postgres".
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
GRANT
```

**Comment by matsduf** [comment]
In the message above it does not say that the zonemaster user is not created. Does it fail when you continue?

**Comment by sandoche2k** [comment]
It does not fail, but the message creates a confusion.

**Comment by mattias-p** [comment]
It doesn't look confusing to me. The `postgres` user is used for the initial setup of the `zonemaster` database and the `zonemaster` user. The `zonemaster` user can't reasonably create itself.

**Comment by mtoma** [comment]
This should be closed. The behaviour is normal and we can hardly do anything about the message.

**Comment by matsduf** [comment]
@sandoche2k, maybe a note could be added in the installation instruction? This was under CentOS, right? Do we see the same message under both CentOS versions? Other OSs?

**Comment by sandoche2k** [comment]
I need to check after creating a new test installation. I will get back to you after doing that.

**Comment by sandoche2k** [comment]
Yes, I do have the same result in CentOS8. But, I am closing to it as per the argument of @mattias-p above.
