### ISSUE TITLE
Split System V service script

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#576]
The `zm-backend.sh` script should be split into `zm-rpcapi.sysv` and `zm-testagent.sysv`.
The installation instruction will need to be updated accordingly.
No upgrade instruction should be needed as long as we treat the zonemaster_backend_rpcapi.psgi and zonemaster_backend_testagent as public interfaces.

This affects CentOS, Debian and Ubuntu. The same separation has been implemented on FreeBSD for a long time.

**Comment by matsduf** [comment]
Resolved by #579

**Comment by sandoche2k** [comment]
@mattias-p close?
