### ISSUE TITLE
Does not return Status in the installation instruction

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-backend#580]
CentOS-7, MySQL 
Section "3.3 Service configuration and startup (CentOS)" of the installation instruction
```
sudo /etc/init.d/zm-rpcapi status
```

**Comment by matsduf** [comment]
Is there a difference between Mysql and PostgreSQL, respectively? Do you get the status information with "/etc/init.d/zm-testagent"?

**Comment by sandoche2k** [comment]
I don't think there is a difference between MySQL and PostgreSQL. Yes I do get status information "/etc/init.d/zm-testagent"

**Comment by mattias-p** [comment]
The adding of the `/etc/init.d/zm-rpcapi status` command was wishful thinking on my part. And you shouldn't need sudo for the status command.
The old status command from zm-backend.sh only queried the test agent. I'll make a PR updating the instruction and create an issue to add the status command for the rpcapi script.

**Comment by matsduf** [comment]
Resolved by #581.

**Comment by mattias-p** [comment]
I created #582 to add the status command to zm-rpcapi-sysv.

**Comment by matsduf** [comment]
Resolved by #586
