### ISSUE TITLE
RCPAPI status on System V

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#582]
Add a status command to the zm-rpcapi command for System V.
The installation instruction should also be updated to include invocations of the `zm-rpcapi status` command.

**Comment by mattias-p** [comment]
I'm not sure what the idiomatic way is to check the status of a starman daemon. Daemon::Control (used in the test agent) has a special feature for this use case.
Maybe we could port the BSD solution.

**Comment by matsduf** [comment]
Resolved by #586.
