### ISSUE TITLE
Not able to start the RPCPAPI Daemon on CentOS7

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-backend#589]
[sandoche@vps803736 Zonemaster-Backend]$ sudo /etc/init.d/zm-rpcapi start
/etc/init.d/zm-rpcapi: line 26: /lib/lsb/init-functions: No such file or directory

**Comment by matsduf** [comment]
@mattias-p, can you take a look at it?

@sandoche2k, I assume it is CentOS, isn't it? Both 7 and 8 or just one of them? Please update the description.

**Comment by matsduf** [comment]
@sandoche2k, have you tested the script in CentOS 8?

**Comment by mattias-p** [comment]
Apparently CentOS isn't LSB compatible out of the box. You have to install a package for that. It seems System V initscripts are out of fashion on CentOS.

**Comment by sandoche2k** [comment]
> @sandoche2k, have you tested the script in CentOS 8?

No

**Comment by matsduf** [comment]
Resolved by #590.
