### ISSUE TITLE
RPCAPI Status not found on CentOS7

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-backend#591]
[sandoche@vps803736 ~]$ sudo /etc/init.d/zm-rpcapi status
/etc/init.d/zm-rpcapi: line 51: status_of_proc: command not found

**Comment by matsduf** [comment]
I would assume that it is conntected to issue #589.

**Comment by mattias-p** [comment]
Well, in #586 I managed to make a call to a function that's not part of LSB but rather a local extension.

**Comment by matsduf** [comment]
Resolved by #592
