### ISSUE TITLE
Undocumented and maybe unused scripts

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#597]
There are three scripts in the [script/crontab_job_runner] directory without documentation and not mentioned anywhere else besides in the [MANIFEST] file. They are not installed on target computer.

If they are useful -- and used -- they should be documented and possible installed. Or else they should be removed (and the [MANIFEST] file be updated).

The three scripts in [script/crontab_job_runner] are:

* execute_tests.pl
* execute_zonemaster_P10.pl
* execute_zonemaster_P5.pl

[MANIFEST]: https://github.com/zonemaster/zonemaster-backend/blob/master/MANIFEST
[script/crontab_job_runner]: https://github.com/zonemaster/zonemaster-backend/tree/master/script/crontab_job_runner

**Comment by sandoche2k** [comment]
@mtoma ?

**Comment by matsduf** [comment]
@mtoma, can you look at this?

**Comment by matsduf** [comment]
Resolved by #642.

**Comment by sandoche2k** [comment]
@matsduf close?
