### ISSUE TITLE
Update the database patch (upgrade) scripts

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#618]
* The scripts "use Data::Dumper" without using it.
* The line `die "The configuration file does not contain the MySQL backend" (...)` is too long and should be broken up.
* BackendDBType() returns the exact string 'MySQL' so it's better to compare against that.

See comments [a] and [b] in PR #617.

[a]: https://github.com/zonemaster/zonemaster-backend/pull/617/files/7d93ae3abfc4d4c7bff9821557867bb272b6ef38#diff-b332cd4231e30bd9fe78bc70b80a76b0

[b]: https://github.com/zonemaster/zonemaster-backend/pull/617/files/7d93ae3abfc4d4c7bff9821557867bb272b6ef38#diff-b332cd4231e30bd9fe78bc70b80a76b0

**Comment by pnax** [comment]
This was partially solved with commit https://github.com/zonemaster/zonemaster-backend/commit/413d4c6bac894840e257abc7617e716d353271f9.
PR #833 will remove unused modules from the last patch. We may need to apply this change to older patches as well.

**Comment by pnax** [comment]
This has been fixed with:
* commit 413d4c6bac894840e257abc7617e716d353271f9 from PR #730 
* commit 3eb07bfa2826677003b89acea79e9268699758a5 from PR #879
