### ISSUE TITLE
Remove script or document and install

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#627]
The following three scripts,

* add-test.pl
* create_db_mysql.pl
* create_db_postgresql_9.3.pl

are neither documented nor installed. Are there any use case for them? If so, they should have some documentation and be installed (added to Makefile.PL).

Or else, they could as well be removed. Also see #597.

**Comment by matsduf** [comment]
@mtoma, can you look at this?

**Comment by pnax** [comment]
`create_db_mysql.pl` and `create_db_postgresql_9.3.pl` are used by Travis. And their use is questioned in #689.
`add-test.pl` is not used anywhere and seems redundant to what offers `zmb`. So I think this file can be safely removed from the repo.

**Comment by pnax** [comment]
`add-test.pl` has been removed in #733.

**Comment by matsduf** [comment]
Duplicates #689.
