### ISSUE TITLE
Use of uninitialized value in zm-testagent.out

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#630]
I'm seeing these warnings repeated in zm-testagent.out:
```
Use of uninitialized value in pattern match (m//) at /usr/local/share/perl/5.26.1/Zonemaster/Backend/DB.pm line 131.
```
The file I'm looking at has 41 of them unevenly distributed across 13 restarts.

For the record this particular installation is running Zonemaster::Backend 5.0.2 on Ubuntu 18.04 and MySQL.

**Comment by matsduf** [comment]
Will be fixed by #635
