### ISSUE TITLE
Use of uninitialized value in zm-rpcapi.log

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#631]
I'm seeing lots of these warnings repeated in zm-rpcapi.log:
```
Use of uninitialized value in concatenation (.) or string at /usr/local/share/perl/5.26.1/Zonemaster/Backend/RPCAPI.pm line 389.
```
The file I'm looking at has 82371 of them distributed across 13 restarts.

For the record this particular installation is running Zonemaster::Backend 5.0.2 on Ubuntu 18.04 and MySQL.

**Comment by matsduf** [comment]
Resolved by #635.
