### ISSUE TITLE
Remove duplicated internal calls to validate_syntax

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#637]
The RPC API has a `validate_syntax` method. It is called internally for input validation purposes by the implementations of other RPC API methods. Since #399 we have a more formal and reviewable validation layer, absolving the method implementations of much of the input validation responsibility. By validating the input twice (once in the input validation layer and once from within the method implementation) using different validation implementations we gain very little but the risk of bugs is increased to at least the double.
A review should be made to identify where the internal calls to `validate_syntax` simply duplicate work that's already done by the input validation layer. In all those cases the call to `validate_syntax` should be removed.

This issue was prompted by https://github.com/zonemaster/zonemaster-backend/pull/634#issuecomment-692149272.

Future work:
* Replace any remaining internal calls to `validate_syntax` with specific the validations that are not covered by the input validation layer.
* Consider updating the input validation layer to include any resulting specific input validations.
* Consider the viability of `validate_syntax` as a method in the RPC API.

**Comment by pnax** [comment]
The `validate_syntax` method has first evolved in several methods in #820 and the duplication and anonymous methods have been completely removed with #957.
