### ISSUE TITLE
Fix API documentation inconsistency

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-backend#647]
In [the API document](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/API.md), the [_Client id_](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/API.md#client-id) and [_Client version_](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/API.md#client-version) say the number of allowed characters is « at most 512 », but the following regex states otherwise : `/^[a-zA-Z0-9-+~_.: ]{1,50}$/`.

Looking at the commit https://github.com/zonemaster/zonemaster-backend/commit/a14b95ad2d646d5b9d005b71c7acb7fef87e297f the validator is using the regex. And the validator still does in [master](https://github.com/zonemaster/zonemaster-backend/blob/master/lib/Zonemaster/Backend/Validator.pm#L29..L34) and [develop](https://github.com/zonemaster/zonemaster-backend/blob/develop/lib/Zonemaster/Backend/Validator.pm#L33..L38).

It would be nice to update the text to avoid inconsistency.

**Comment by pnax** [comment]
About the [_Username_](https://github.com/zonemaster/zonemaster-backend/blob/develop/docs/API.md#username) the text says it allows a « string of alphanumerics, dashes, full stops and at-signs », this does not match the following regex : `/^[a-zA-Z0-9]{1,50}$/`

However the code in the validator ([develop](https://github.com/zonemaster/zonemaster-backend/blob/develop/lib/Zonemaster/Backend/Validator.pm#L75) and [master](https://github.com/zonemaster/zonemaster-backend/blob/master/lib/Zonemaster/Backend/Validator.pm#L71)) is using the following regex : `/^[a-zA-Z0-9-.@]{1,50}$/` which is consistent with the API text

**Comment by matsduf** [comment]
Resolved by #648.
