### ISSUE TITLE
Unused files in share?

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#654]
Is `share/starman-zm-backend-RPC-API.conf` ever used? There is no reference to this file except in the MANIFEST file.

The same is true for `share/zonemaster_backend_testagent.conf`.

They should either be removed or documented.

**Comment by matsduf** [comment]
#672 has removed `share/zonemaster_backend_testagent.conf`, but `share/starman-zm-backend-RPC-API.conf` still remains.

**Comment by pnax** [comment]
`share/starman-zm-backend-RPC-API.conf` has been removed in #733.
Since both files are removed, I close this issue.
