### ISSUE TITLE
Extra newline in message

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#673]
If an unused profile is used in `start_domain_test` call RPCAPI, an extra newline is included in the message.

```json
{
  "id": 1,
  "error": {
    "message": "Internal error 009 \n",
    "code": -32603
  },
  "jsonrpc": "2.0"
}
```

**Comment by pnax** [comment]
This newline is added in the [`handle_exception` function](https://github.com/zonemaster/zonemaster-backend/blob/develop/lib/Zonemaster/Backend/RPCAPI.pm#L70..L76). Do you mean that the function should not return a newline at all ?

```
sub handle_exception {
    ...
    die "Internal error $exception_id \n";
}
```

**Comment by matsduf** [comment]
I guess that the problem is that die() without a newline will add some extra data that we do not want. In the message from RPCAPI there should be no "\n".

**Comment by mtoma** [comment]
The newlines at the end of die statements do have a special meaning: https://perldoc.perl.org/functions/die .
Those should be removed from the final messages so the newline in the API output is a doubled one.

**Comment by mattias-p** [comment]
I created https://github.com/lestrrat-p5/JSON-RPC/pull/13 get this fixed. There doesn't seem to be much activity there though, so I won't hold my breath.

Should we keep this open or could we close it?

**Comment by matsduf** [comment]
I moved it to next release, and I will investigate how much of a problem it is.

**Comment by matsduf** [comment]
Will not fix.
