### ISSUE TITLE
Any use case for "force_hash_id_use_in_API_starting_from_id"?

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#691]
The records in the databases have two unique identifiers, a normal integer that is incremented by one each time a test is created and a hash that is just unique. The hash is what is always used unless `force_hash_id_use_in_API_starting_from_id` is set in the configuration file to some value higher than zero and then straight integer IDs can be used for those lower than that value.

Is there really a valid use case for using the integer IDs? If not, the code could be simplified.

Proposal:
* Remove all code dependent on `force_hash_id_use_in_API_starting_from_id` and force the use of the hash IDs in all cases.
* Remove `force_hash_id_use_in_API_starting_from_id` from `Config.pm`, the ini file and all documentation.

**Comment by mtoma** [comment]
I'd say this is reasonable proposal as the only use of this parameter is for very old installations that started by using the id without hash_id and wanted/needed to enforce the hash_id starting from some specific id. As far as I can tell the zonemaster.net installation was the only one in this case. Not sure if there are some IDs without hash_ids or if the database was wiped at some point making this parameter useless even there.

**Comment by mattias-p** [comment]
So we should look for test_results in the zonemaster.net database that don't have hash_ids, and if there are any, generate new random hash_ids for them. Since `force_hash_id_use_in_API_starting_from_id` is undocumented in the latest release (2020.1) it should be safe to assume that nobody outside of the Zonemaster team has been using it.

Right?

**Comment by matsduf** [comment]
Resolved by #726.
