### ISSUE TITLE
Separate config section for each db engine

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#719]
Today all supported database engines are configured using the same properties in the same section of the backend_config ini file. If you have multiple database engines installed and want to switch between them you need to either update multiple properties in your config to make the switch, or you need to have several config files differing only in the database details. This adds an unnecessary hoop you have to jump through in all sorts of testing related contexts. Also this overloading of properties makes the configuration format documentation more opaque to the reader.

The configuration format should be updated to have a separate section for each supported database engine.
The Config module should support overriding the database engine type programmatically. (This would come in handy for unit tests at the very least.)

The old properties should be deprecated, their semantics should be updated so that they work as fallbacks for the properties in all of the database engine-specific sections. The deprecation message should instruct the user to use the corresponding database specific property instead.

**Comment by matsduf** [comment]
I think it is a good idea to have separate sections for the different database engines, but do we really gain enough from making it possible to select engine on the command line? I think that should still be in the configuration file only.

**Comment by mattias-p** [comment]
Maybe not. I'll remove that requirement. If we change our minds we can always add it later.

**Comment by mattias-p** [comment]
Fixed by #730.
