### ISSUE TITLE
Documentation of environment variables

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#737]
Various programs in Backend are configurable using various environment variables. Currently these aren't well documented. For each command there should be a complete list of the environment variables it uses. The set of all unit tests should probably be considered a single command in this respect. The list should specify:
* The name of the variable
* The set of valid values (syntax)
* The meaning of each valid value
* The meaning of not setting the variable (e.g. the default value)
* Any interactions with other configuration parameters

**Comment by matsduf** [comment]
Good suggestion.

Could we extend the scope of [Configuration.md] and include it there? That document is not too large, and I feel it is better to keep all configuration there. Setting an environment variable is a sort of configuration. And `ZONEMASTER_BACKEND_CONFIG_FILE` is one such variable that points out the configuration file.

[Configuration.md]: https://github.com/zonemaster/zonemaster-backend/blob/master/docs/Configuration.md

**Comment by mattias-p** [comment]
Another option to consider is to have separate documentations for each command. We do have a couple of them and they aren't all configurable using the same environment variables.

**Comment by matsduf** [comment]
Resolved by #974 and #993
