### ISSUE TITLE
Running tests without littering in the file system

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#747]
There should be an easy way to run unit tests with SQLite backed by an in-memory database or alternatively an auto-cleaned up temp file. This is [supported by DBD::SQLite](https://metacpan.org/pod/DBD::SQLite#Database-Name-Is-A-File-Name) as long as we don't need to fork.

This may be complicated by the fact that this feature doesn't really make sense in production mode since the database needs to be shared across two different daemons. If support for this is added to the config file the documentation should probably clarify that this is only intended for testing.

**Comment by pnax** [comment]
Closing the issue since I think #947 fixes it. Feel free to re-open it if you think this is not the case.
