### ISSUE TITLE
Testagent service fails to restart after a failure (Linux)

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-backend#773]
As noted in #767 (see https://github.com/zonemaster/zonemaster-backend/pull/767#issuecomment-849022317 and https://github.com/zonemaster/zonemaster-backend/pull/767#issuecomment-849762490), when the Testagent fails to start (due to a config error for instance), trying to restart the service after fixing the problem does not work. The service stays in a failed state.
It would be nice to be able to restart the service once the error has been fixed.

**Comment by matsduf** [comment]
This issue does not apply on FreeBSD
1. Stopped both daemons
2. Updated `backend_config.ini` with an invalid value of database engine, `ErrorDB`
3. Starts testagent -- it fails to start
4. Starts RPCAPI -- it appears to start but only starman runs
5. Stops RPCAPI
6. Corrects `backend_config.ini`
7. Starts both daemons
8. Backend works as it should

Does this issue apply to all Linux OS? -- I added "(Linux)" in the title.

**Comment by matsduf** [comment]
See #774

**Comment by matsduf** [comment]
@pnax, is this still relevant in develop branch?

**Comment by pnax** [comment]
I can't reproduce anymore. So I'm closing it.
