### ISSUE TITLE
Improved criteria for test reuse

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#775]
I just ran two tests simultaneously. One through the GUI and one through zmtest. Both tests were for the same domain but the testid wasn't reused.

Here are the parameters:
```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "client_id": "Zonemaster GUI",
    "client_version": "3.2.2",
    "domain": "example.com",
    "ds_info": [],
    "ipv4": true,
    "ipv6": true,
    "nameservers": [],
    "priority": 10,
    "profile": "default",
    "queue": 0
  }
}
```
```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "domain": "example.com",
    "ipv4": true,
    "ipv6": true,
    "priority": 10,
    "profile": "default",
    "queue": 0
  }
}
```
Their representations are different but semantically they are the same. When calculating the "deterministic hash" at least the `client_id` and `client_version` parameters should be disregarded. Also the parameters should be normalized so that you get the same "deterministic hash" when you use the default values no matter if they're given explicitly or implicitly.

**Comment by matsduf** [comment]
Is that becasue `zmtest` by default explicitly sets the default profile, whereas the GUI by default leaves it empty?

**Comment by pnax** [comment]
From my understanding, all the parameters passed are used, and the GUI gives them all, whereas zmtest passes only the one set.

I think we should explicitly extract the values used to define this deterministic hash (and add the one missing).

As @mattias-p suggested, I'd go with the removal of `client_id` and `client_version`, and explicitly keep/define all other values, which leaves us with the following JSON to encode :

```
{
  "domain": "example.com",
  "ds_info": [],
  "ipv4": true,
  "ipv6": true,
  "nameservers": [],
  "priority": 10,
  "profile": "default",
  "queue": 0
}
```

**Comment by matsduf** [comment]
If we want maximal match (maximal reuse) then empty `profile` should be equal to "default" and the values of `ipv4` and `ipv6` should be matched against the profile. The first part is simple and the second is maybe not worth the effort.

**Comment by pnax** [comment]
@mattias-p would you say that #798 addressed this issue?

**Comment by mattias-p** [comment]
Yeah, I'd say this issue is solved!
