### ISSUE TITLE
Validate nameserver's ns parameter before passing it to Engine

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-backend#783]
Currently we only check that the `ns` in the [`nameservers` object](https://github.com/zonemaster/zonemaster-backend/blob/master/docs/API.md#name-server) is a string, [code from Validator.pm](https://github.com/zonemaster/zonemaster-backend/blob/5b485f7f88caa545150e011fdb835b7767941b30/lib/Zonemaster/Backend/Validator.pm#L53..L57) :

```
sub nameserver {
    return joi->object->strict->props(
            ns => joi->string->required,
            ip => ip_address()
    );
}
```

But Engine is more restrictive, it does not permit trailing dot, or allow a single dot only,  [see Engine.pm](https://github.com/zonemaster/zonemaster-engine/blob/9f46f6e60ae545d786ccbb50d5bc66c6a950ed21/lib/Zonemaster/Engine.pm#L112..L115) :

```
    foreach my $name ( keys %{$href} ) {
        $name =~ /[^.]$|^\.$/
          or croak 'Each key of argument $href must omit the trailing dot, or it must be a single dot';
    }
```

It would be nice to validate the `ns` value to be aligned with what is allowed by the Engine.
And it would be even better if the error can be pulled up to the user in the GUI (see #703 and https://github.com/zonemaster/zonemaster/issues/925)

See https://github.com/zonemaster/zonemaster-backend/pull/782#issuecomment-851632810 for an example.

Credits to @matsduf for spotting the error.

**Comment by matsduf** [comment]
I think that Backend (and CLI) should normalize all domain names to be without trailing dot. See the proposed update of Basic00 in https://github.com/zonemaster/zonemaster/pull/942

**Comment by blacksponge** [comment]
NS domain validation has been around for a while now, so I am closing this. As for normalization, this is coming to backend with #1132.
