### ISSUE TITLE
Use a PostgreSQL version that is being maintained

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#786]
We're using a version of PostgreSQL 9.3 on CentOS 7. Even though installation of this version still works it's no longer being maintained. See https://yum.postgresql.org/.

We should pick a newer version. Perhaps the same version we're using on CentOS 8?

**Comment by matsduf** [comment]
Is there a default version for CentOS 7? Using the same version as CentOS 8 could simplify testing, but we should take into consideration that CentOS 8 is EOL 2021-12-31.

**Comment by mattias-p** [comment]
CentOS 7 comes with PostgreSQL 9.2. We require PostgreSQL >= 9.3, so for CentOS 7 we're using packages maintained by PostgreSQL (see link above). We could pick any version we like in that list.

I don't think we need to worry too much about CentOS 8 going EOL. We don't have any skin in that game. If CentOS 8 goes away people will migrate to something else. If we just keep an eye out we'll pick up on where people are going. Then we'll just follow suite.

**Comment by matsduf** [comment]
> CentOS 7 comes with PostgreSQL 9.2. We require PostgreSQL >= 9.3, so for CentOS 7 we're using packages maintained by PostgreSQL (see link above). We could pick any version we like in that list.

Then I suggest that we go for version 12, which is the version used by new OSs, such as Ubuntu 20.04.

> I don't think we need to worry too much about CentOS 8 going EOL.

My point is that since CentOS 8 goes EOL in 6 months there is not much reason to do the same as CentOS 8. And I agree that we should try to pick the alternative of that branch that seems to gain popularity, but at the same time have stability.

**Comment by pnax** [comment]
There was a PR #892, so we currently support PostgreSQL >= 10 which is supported and will get its [final release in November 2022](https://www.postgresql.org/support/versioning/)

**Comment by matsduf** [comment]
It is a good point. We should keep an eye on the version supported. This issue could be closed, couldn't it, @mattias-p?

**Comment by mattias-p** [comment]
Yeah, like @pnax said. Nice!
