### ISSUE TITLE
Cleaning up the database used in unit tests

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#806]
Today we have unit tests that use a special database as part of their infrastructure. This works well in CI because we get a fresh machine every time. However when running tests locally you have to clean up this database between each run or the tests will fail because test data from one run collides with test data from the next.

The unit tests should perform the clean up as part of their own setup. To ensure that the business logic can run without privileges to clean up the database, a separate database user should be used for the clean up.

**Comment by mattias-p** [comment]
No, we still have this problem.

**Comment by pnax** [comment]
Done in #947 with commits 6a6b5cddbb20cb56fc004e169dc66d9f6dae6d62 and 8d768803a5f00595405f554c0c4d63f8dc7738d5
