### ISSUE TITLE
Load config in zm-rpcapi master process

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#813]
Today the zm-rpcapi master process doesn't parse the config file. Instead each worker process parses the config the first thing they do. If the config is invalid they fail, and the master process starts spawning new replacements for the crashed workers.

The config should be parsed once and for all in the master process, and then the Config instance should be inherited by the worker processes.

**Comment by pnax** [comment]
Isn't it already taken care with commit: https://github.com/zonemaster/zonemaster-backend/commit/2c3cbd4bcb4d772bac2db06c653eb6c5fcd33a57?

**Comment by matsduf** [comment]
@mattias-p, #851 has been merged. Can this be closed?
