### ISSUE TITLE
Application specific error codes

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#819]
The JSONRPC specification allows applications to specify their own error codes. Today all handler methods in the RPCAPI module catch exceptions at their top level and generate errors with the generic code -32603 (Internal error).

We should:
* Pick a small set of error states that we want to generate application defined error responses for.
* Update the "Error reporting" section in the API document to include those error states.

For each error state we should also:
1. Create a class method named after its message string in lower snake case. This method should return a data structure that represents an JSONRPC error object for this error state. If the error state has a described data type, the method should take appropriate arguments so the data member of the error object can be properly populated.
2. Make sure this error state throws an exception that can be recognized in a reliable way.
3. Determine all handler methods where this exception can end up.
4. Update exactly those handler methods to recognize the exception. When such an exception is recognized, the class method should be used to create an error object so the application defined error response can be returned instead of the generic -32603 response.

**Comment by matsduf** [comment]
@mattias-p and @blacksponge, how much of this issue has been resolved by #847? Could this issue be updated to reflect that?

**Comment by blacksponge** [comment]
#847 adds all the logic for application error codes but because JSON::RPC can not handle custom error code it does not work (related PR https://github.com/lestrrat-p5/JSON-RPC/pull/14)

**Comment by matsduf** [comment]
As I understand it, #847 has resolved as much as is possible withing the frame work. If so, I suggest that we close this issue.

**Comment by mattias-p** [comment]
I created #917 covering the remaining parts of this issue.

**Comment by matsduf** [comment]
In most parts resolved by #847. The remainder moved to #917.
