### ISSUE TITLE
Rename column "params_deterministic_hash" into "fingerprint"

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-backend#832]
With #798 we changed all code occurrences of "params deterministic hash" into "fingerprint". Since we are updating the database with #826 I suggest that we also update the column name "params_deterministic_hash" in the database to "fingerprint".

This will be a breaking change.

**Comment by matsduf** [comment]
I think that could be fine, but then we should investigate if there are more such changes that should be done at the same time. And make sure that all three engines are synchronize. Migration scripts are of course necessary.

**Comment by matsduf** [comment]
This has been resolved.
