### ISSUE TITLE
add_api_user remote ip check don't work behind reverse proxy

### ISSUE THREAD

**Issue by blacksponge** [zonemaster/zonemaster-backend#838]
When running the API behind a reverse proxy on the same machine (like it is using the [configuration example](https://github.com/zonemaster/zonemaster-gui/blob/master/zonemaster.conf-example) provided by the GUI) the remote ip might always be localhost even if the query was done from elsewhere so the check done by `add_api_user ` is useless.

A better solution would be to use the [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For), and only default to the remote ip if it is not present.

**Comment by matsduf** [comment]
Resolved by #839.
