### ISSUE TITLE
Do not set "test_start_time" before actually running the test

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-backend#842]
Currently SQLite and MySQL set `test_start_time` to the current time when a test is created, I don't think we should update this value before running the test. Therefore the value should be left to `NULL`.

Currently all database engines reset `test_start_time` to the current time when rescheduling unfinished test (see `schedule_for_retry()`). I think it would be better to reset the value to `NULL` instead.

**Comment by matsduf** [comment]
I agree with you suggestions.

**Comment by pnax** [comment]
fixed in #841
