### ISSUE TITLE
Rename test_results.params_deterministic_hash

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#852]
In #798 we introduced the term "fingerprint" as a new name for "params_deterministic_hash". Around the code references to params_deterministic_hash were replaced with "fingerprint". However the database schema wasn't updated because we didn't want to force a database schema migration when upgrading to the new version of Backend. However since there will be a database schema migration for the upcoming release, this is a good time to rename the field in the database.

1. Update all references to the database field from "params_deterministic_hash" to "fingerprint".
2. Update the patch scripts for the databases to alter the field name in existing databases.

**Comment by pnax** [comment]
See #832 and this will be resolved in #841, see https://github.com/zonemaster/zonemaster-backend/pull/841/commits/07de0b2c06e078b245b27016eb814ae2b037e184

**Comment by mattias-p** [comment]
Duplicate of #832.
