### ISSUE TITLE
Make testagent allocate test atomically

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-backend#857]
If you have lots of zones to test, testing all of them might take a long time. One way increase throughput is to run more than one zm-testagent (on different machines). Today test allocation in zm-testagent is non-atomic. You can work around this by configuring each zm-testagent to use a different queue in the database, and make clients specify different queue values when adding tests via zm-rpcapi. This is awkward for both the administrator and the user.

The test allocation should be made atomic. That way administrators could configure many zm-testagents to poll the same queue(s), and clients could get improved throughput without having to distribute their tests among the different queues.

**Comment by matsduf** [comment]
If this idea is implemented we can deprecate "queue".

If this idea does not work, then using one queue value per Test Agent and letting RPCAPI randomly distribute the tests on available queue value would be almost as simple to use, but more complex to configure.

**Comment by mattias-p** [comment]
Implemented by #1121.
