### ISSUE TITLE
Installing Backend on Ubuntu 18.04 failed

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#884]
First I installed Engine and LDNS from CPAN:
```
Zonemaster::LDNS is up to date. (2.2.0)
Successfully installed Zonemaster-Engine-4.002003 (upgraded from v4.2.1)
```

Dependencies for Backend installed. Backend from develop branch, commit f6cc5a1, installed.

Then:
```
$ sudo install -v -m 755 -o zonemaster -g zonemaster -d /var/lib/zonemaster
$ sudo -u zonemaster $(perl -MFile::ShareDir -le 'print File::ShareDir::dist_dir("Zonemaster-Backend")')/create_db.pl
DBD::SQLite::db do failed: no such column: fingerprint at /usr/local/share/perl/5.26.1/Zonemaster/Backend/DB/SQLite.pm line 82.
DBD::SQLite::db do failed: no such column: fingerprint at /usr/local/share/perl/5.26.1/Zonemaster/Backend/DB/SQLite.pm line 82.
```

**Comment by pnax** [comment]
Could you check that you are not reusing an old database file in the `backend_config.ini` and that the `fingerprint` column is indeed present in the `test_results` table (`PRAGMA table_info(test_results)`)?

**Comment by matsduf** [comment]
An old database file was (probably) the problem. When I removed the database file and rerun I got no errors.
