### ISSUE TITLE
Ubuntu dependencies installation

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-backend#901]
The [libjson-validator-perl package for Ubuntu 20.04](https://packages.ubuntu.com/focal/perl/libjson-validator-perl) is from [February 2020](http://changelogs.ubuntu.com/changelogs/pool/universe/libj/libjson-validator-perl/libjson-validator-perl_3.23+dfsg-1/changelog). And Draft7 has been added to JSON::Validator in [June 2020](https://metacpan.org/dist/JSON-Validator/changes#L187).

We then need to install JSON::Validator from CPAN. I'll provide a change to the installation document. I'm just checking that there are no other similar dependencies errors before.

**Comment by pnax** [comment]
Looking at the `MAKEFILE.pl` it seems that we ask for the version >= 3.12 of JSON::Validator. But we need at least 4.0 since we use Draft7.

https://github.com/zonemaster/zonemaster-backend/blob/46b164b1bf0f9b8f6563e980afdda95c118f9266/Makefile.PL#L24

https://github.com/zonemaster/zonemaster-backend/blob/46b164b1bf0f9b8f6563e980afdda95c118f9266/lib/Zonemaster/Backend/RPCAPI.pm#L18

**Comment by mattias-p** [comment]
Are there any changes in draft 7 that we need? Maybe we could defer upgrading to draft 7 until it's included in Ubuntu?

**Comment by pnax** [comment]
> Are there any changes in draft 7 that we need?

@blacksponge told me that yes there are.

https://github.com/zonemaster/zonemaster-backend/blob/46b164b1bf0f9b8f6563e980afdda95c118f9266/lib/Zonemaster/Backend/RPCAPI.pm#L770

Just bumping the version in the MAKEFILE.pl file will let cpanm fetch the correct version of JSON::Validator.

**Comment by matsduf** [comment]
Resolved by #902.
