### ISSUE TITLE
Locale::Msgfmt is not listed as dependency but required by Makefile.PL

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-backend#990]
[Installation] document does not list Locale::Msgfmt as a dependency for any OS, but it is required in Makefile.PL. The result is that it is fetched from CPAN.

In d341439101e15812115f80941ddda9eaaa57deb1 it was added to Makefile that is should be required, and that as dependency in the installation document.

In 82e24a01ae066fab88f39d83d711c77b66ce7166 the installation ducument was updated and the dependency was removed.

[Installation]: https://github.com/zonemaster/zonemaster-backend/blob/develop/docs/Installation.md

**Comment by pnax** [comment]
Looking at the code, I can't find anywhere where Locale::Msgfmt is used.

**Comment by matsduf** [comment]
Resolved by #991
